[package]
name = "adventurous"
version = "0.0.2"
description = "A utility library for solving Advent of Code puzzles."
repository = "https://github.com/maxdeviant/adventurous"
keywords = ["advent", "code"]
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
